In [ ]:
def is_even(number):
    if number % 2 == 0:
        return True
    else:
        return False

In [ ]:
print (is_even(4))
print (is_even(7))

In [23]:
for even in range(1,21):
    if is_even (even):
        print(even, "is even number")

2 is even number
4 is even number
6 is even number
8 is even number
10 is even number
12 is even number
14 is even number
16 is even number
18 is even number
20 is even number


In [ ]:
def describe_list (numbers):
    n = len(numbers)
    mean = sum(numbers) / n
    sorted_numbers = sorted(numbers)
    median = sorted_numbers[n//2]
    variance = sum((x-mean)**2 for x in numbers) / n
    std = variance ** 0.5
    return mean, median, std
print (describe_list([20,30,40]))

In [22]:
student = {"Alice" : 82, "Bob" : 90, "Charlie" : 78, "David" : 85, "Eve" : 88}
for name, score in student.items():
    if score > 85:
        print(name, "has a good score")  

Bob has a good score
Eve has a good score


In [10]:
import numpy as np

# Task 4: Create array of 50 random numbers between 0 and 100
arr = np.random.randint(0, 100, 50)
print("Array:", arr)
print("Mean:", arr.mean())
print("Std", arr.std())
print("Max:", arr.max())
print("Min:", arr.min())

# Task 5 : Reshape into 5x10 matrix
matrix = arr.reshape(5, 10)
print("Shaped Matrix:", matrix.shape)
print("Shaped Array:", matrix)

# Task 6 : Select all values greater than 60
greater_than_60 = arr[arr > 60]
print("Values greater than 60:", greater_than_60)

Array: [63  8 84 50 96  4 34 57  2 21 98 90 48  2 60 92 44 21 72 57 21 82 51 77
 90 64 81  0 45 58  2 93 59 28 57 31 27 73  5  7 27  5 12 34  5 30 60 89
 73 21]
Mean: 46.2
Std 30.726535763082698
Max: 98
Min: 0
Shaped Matrix: (5, 10)
Shaped Array: [[63  8 84 50 96  4 34 57  2 21]
 [98 90 48  2 60 92 44 21 72 57]
 [21 82 51 77 90 64 81  0 45 58]
 [ 2 93 59 28 57 31 27 73  5  7]
 [27  5 12 34  5 30 60 89 73 21]]
Values greater than 60: [63 84 96 98 90 92 72 82 77 90 64 81 93 73 89 73]
